services:
  snek:
    build: .
    container_name: snek
    command: bash -c "fusion-snake"
    ports:
      - 6666:6666
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data # Persist game stats across restarts
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - STATS_FILE=/data/game_stats.json
